base_dnf:
  num_preds: 103
  num_conjuncts: 66
  num_classes: 22
  weight_init_type: 'normal'

double_dnf:
  num_preds: 500
  num_conjuncts1: 1000
  num_disjuncts1: 500
  num_conjuncts2: 100
  num_classes: 22
