base_dnf:
  num_preds: 46
  num_conjuncts: 9
  num_classes: 3
  weight_init_type: 'normal'

double_dnf:
  num_preds: 500
  num_conjuncts1: 1000
  num_disjuncts1: 500
  num_conjuncts2: 100
  num_classes: 22
