defaults:
  - base_parameter

use_cuda: true
experiment_name: dnf_vanilla_bce
model_name: dnf_vanilla

dnf_vanilla:
  optimiser: adam
  optimiser_lr: 0.001
  optimiser_weight_decay: 0.00004
  scheduler_step: 100
  # loss_func: bce
  batch_size: 256
  epochs: 1000
  initial_delta: 0.1
  delta_decay_delay: 50
  delta_decay_steps: 25
  delta_decay_rate: 1.02
  reg_fn: l1_mod
  reg_lambda: 0.3
  macro_metric: f1-score # choices: precision, recall, f1-score
