defaults:
  - base_parameter

use_cuda: false
experiment_name: double_dnf_bce
model_name: double_dnf

double_dnf:
  optimiser: adam
  optimiser_lr: 0.001
  optimiser_weight_decay: 0.00004
  scheduler_step: 100
  # loss_func: bce
  batch_size: 512
  epochs: 500
  initial_delta: 0.01
  delta_decay_delay: 50
  delta_decay_steps: 50
  delta_decay_rate: 0.1
  reg_fn: l1_mod
  reg_lambda: 0.3
  macro_metric: precision # choices: precision, recall, f1-score
